source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Misc.RFQ/Controllers/RfqAdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Misc.RFQ.Domains;
using Nop.Plugin.Misc.RFQ.Factories;
using Nop.Plugin.Misc.RFQ.Models.Admin;
using Nop.Plugin.Misc.RFQ.Services;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Customers;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Misc.RFQ.Controllers;

[Area(AreaNames.ADMIN)]
[AuthorizeAdmin]
[AutoValidateAntiforgeryToken]
public class RfqAdminController : BasePluginController
{
    #region Fields

    private readonly AdminModelFactory _modelFactory;
    private readonly ICustomerModelFactory _customerModelFactory;
    private readonly ICustomerService _customerService;
    private readonly ILocalizationService _localizationService;
    private readonly INotificationService _notificationService;
    private readonly IProductAttributeParser _productAttributeParser;
    private readonly IProductAttributeService _productAttributeService;
    private readonly IProductService _productService;
    private readonly ISettingService _settingService;
    private readonly IShoppingCartService _shoppingCartService;
    private readonly RfqMessageService _rfqMessageService;
    private readonly RfqService _rfqService;
    private readonly RfqSettings _rfqSettings;

    #endregion

    #region Ctor

    public RfqAdminController(AdminModelFactory modelFactory,
        ICustomerModelFactory customerModelFactory,
        ICustomerService customerService,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IProductAttributeParser productAttributeParser,
        IProductAttributeService productAttributeService,
        IProductService productService,
        ISettingService settingService,
        IShoppingCartService shoppingCartService,
        RfqMessageService rfqMessageService,
        RfqService rfqService,
        RfqSettings rfqSettings)
    {
        _modelFactory = modelFactory;
        _customerModelFactory = customerModelFactory;
        _customerService = customerService;
        _localizationService = localizationService;
        _productAttributeParser = productAttributeParser;
        _productAttributeService = productAttributeService;
        _productService = productService;
        _notificationService = notificationService;
        _settingService = settingService;
        _shoppingCartService = shoppingCartService;
        _rfqMessageService = rfqMessageService;
        _rfqService = rfqService;
        _rfqSettings = rfqSettings;
    }

    #endregion

    #region Methods

    #region Configure

    public async Task<IActionResult> Configure()
    {
        var model = new ConfigurationModel
        {
            Enabled = _rfqSettings.Enabled
        };

        return View("~/Plugins/Misc.RFQ/Views/Admin/Configure.cshtml", model);
    }

    [HttpPost, ActionName("Configure")]
    [FormValueRequired("save")]
    public async Task<IActionResult> Configure(ConfigurationModel model)
    {
        if (!ModelState.IsValid)
            return await Configure();
        
        _rfqSettings.Enabled = model.Enabled;

        await _settingService.SaveSettingAsync(_rfqSettings);
        
        _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

        return await Configure();
    }

    #endregion

    #region Add product to quote

    [HttpPost]
    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    [CheckPermission(StandardPermission.Catalog.PRODUCTS_VIEW)]
    public async Task<IActionResult> AddNewProduct(ProductSearchModel searchModel)
    {
        //prepare model
        var model = await _modelFactory.PrepareProductListModelAsync(searchModel);

        return Json(model);
    }

    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    [CheckPermission(StandardPermission.Catalog.PRODUCTS_VIEW)]
    public async Task<IActionResult> AddProductDetails(int productId, int quoteId)
    {
        var quote = await _rfqService.GetQuoteByIdAsync(quoteId)
            ?? throw new ArgumentException("No quote found with the specified id");

        var product = await _productService.GetProductByIdAsync(productId)
            ?? throw new ArgumentException("No product found with the specified id");

        //prepare model
        var model = await _modelFactory.PrepareAddProductModelAsync(new AddProductModel(), quote, product);

        return View("~/Plugins/Misc.RFQ/Views/Admin/AddProductDetails.cshtml", model);
    }

    [HttpPost]
    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    [CheckPermission(StandardPermission.Catalog.PRODUCTS_VIEW)]
    public async Task<IActionResult> AddProductDetails(int quoteId, int productId, IFormCollection form)
    {
        var product = await _productService.GetProductByIdAsync(productId)
            ?? throw new ArgumentException("No product found with the specified id");

        //basic properties
        _ = decimal.TryParse(form["UnitPriceInclTax"], out var unitPriceInclTax);
        _ = int.TryParse(form["Quantity"], out var quantity);

        //warnings
        var warnings = new List<string>();

        //attributes
        var attributesXml = await _productAttributeParser.ParseProductAttributesAsync(product, form, warnings);

        //rental product
        _productAttributeParser.ParseRentalDates(product, form, out _, out _);

        var quote = await _rfqService.GetQuoteByIdAsync(quoteId)
                ?? throw new ArgumentException("No quote found with the specified id");

        //try to get a customer with the specified id
        var customer = await _customerService.GetCustomerByIdAsync(quote.CustomerId)
            ?? throw new ArgumentException("No customer found with the specified id");

        //warnings
        warnings.AddRange(await _shoppingCartService.GetShoppingCartItemAttributeWarningsAsync(customer, ShoppingCartType.ShoppingCart, product, quantity, attributesXml));

        if (!warnings.Any())
        {
            var quoteItem = new QuoteItem
            {
                AttributesXml = attributesXml,
                ProductId = product.Id,
                OfferedQty = quantity,
                QuoteId = quoteId,
                OfferedUnitPrice = unitPriceInclTax
            };

            await _rfqService.InsertQuoteItemAsync(quoteItem);

            return RedirectToAction("AdminQuote", new { id = quoteId });
        }

        //prepare model
        var model = await _modelFactory.PrepareAddProductModelAsync(new AddProductModel(), quote, product);
        model.Warnings.AddRange(warnings);

        return View("~/Plugins/Misc.RFQ/Views/Admin/AddProductDetails.cshtml", model);
    }

    [HttpPost]
    public async Task<IActionResult> ProductDetailsAttributeChange(int productId, bool validateAttributeConditions, IFormCollection form)
    {
        var product = await _productService.GetProductByIdAsync(productId);
        if (product == null)
            return new NullJsonResult();

        var errors = new List<string>();
        var attributeXml = await _productAttributeParser.ParseProductAttributesAsync(product, form, errors);

        //conditional attributes
        var enabledAttributeMappingIds = new List<int>();
        var disabledAttributeMappingIds = new List<int>();

        if (validateAttributeConditions)
        {
            var attributes = await _productAttributeService.GetProductAttributeMappingsByProductIdAsync(product.Id);

            foreach (var attribute in attributes)
            {
                var conditionMet = await _productAttributeParser.IsConditionMetAsync(attribute, attributeXml);

                if (!conditionMet.HasValue)
                    continue;

                if (conditionMet.Value)
                    enabledAttributeMappingIds.Add(attribute.Id);
                else
                    disabledAttributeMappingIds.Add(attribute.Id);
            }
        }

        return Json(new
        {
            enabledattributemappingids = enabledAttributeMappingIds.ToArray(),
            disabledattributemappingids = disabledAttributeMappingIds.ToArray(),
            message = errors.Any() ? errors.ToArray() : null
        });
    }

    [HttpPost]
    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    [CheckPermission(StandardPermission.Customers.CUSTOMERS_VIEW)]
    public async Task<IActionResult> CustomerList(CustomerSearchModel searchModel)
    {
        //prepare model
        var model = await _customerModelFactory.PrepareCustomerListModelAsync(searchModel);

        return Json(model);
    }

    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    [CheckPermission(StandardPermission.Customers.CUSTOMERS_VIEW)]
    public async Task<IActionResult> SelectCustomerPopup()
    {
        //prepare model
        var model = await _customerModelFactory.PrepareCustomerSearchModelAsync(new CustomerSearchModel());

        return View("~/Plugins/Misc.RFQ/Views/Admin/SelectCustomerPopup.cshtml", model);
    }

    #endregion

    #region Request a quote

    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    public async Task<IActionResult> AdminRequests()
    {
        //prepare model
        var model = await _modelFactory.PrepareRequestQuoteSearchModelAsync();

        return View("~/Plugins/Misc.RFQ/Views/Admin/AdminRequests.cshtml", model);
    }

    [CheckPermission(RfqPermissionConfigManager.ADMIN_ACCESS_RFQ)]
    public async Task<IActionResult> AdminRequest(int id)
    {
        if (id <= 0)

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Misc.RFQ/Views/Admin/AddProductDetails.cshtml
@model Nop.Plugin.Misc.RFQ.Models.Admin.AddProductModel

@using Nop.Core.Domain.Catalog

@{
    Layout = "_AdminLayout";
    //page title
    ViewBag.PageTitle = string.Format(T("Plugins.Misc.RFQ.AdminRequest.Products.AddNew.Title2").Text, Model.Name, Model.QuoteId);
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName(RfqDefaults.RequestsAdminMenuSystemName);
}

@*we add enctype = "multipart/form-data" because "File upload" attribute control type requires it*@

<form asp-controller="RfqAdmin" asp-action="AddProductDetails" asp-route-productId="@Model.ProductId" asp-route-QuoteId="@Model.QuoteId" enctype="multipart/form-data" method="post" id="product-details-form">
    
    <div asp-validation-summary="All"></div>

    <div class="content-header clearfix">
        <h1 class="float-left">
            @string.Format(T("Plugins.Misc.RFQ.AdminRequest.Products.AddNew.Title2").Text, Model.Name, Model.QuoteId)
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="AdminQuote" asp-route-id="@Model.QuoteId">@T("Plugins.Misc.RFQ.AdminQuote.Products.AddNew.BackToQuote")</a>
            </small>
        </h1>
        <div class="float-right">
            &nbsp;
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            @if (Model.Warnings.Count > 0)
            {
                <div class="callout callout-danger">
                    <ul>
                        @foreach (var warning in Model.Warnings)
                        {
                            <li>@warning</li>
                        }
                    </ul>
                </div>
            }

            <div class="form-horizontal">
                <div class="cards-group">
                    @if (Model.ProductType == ProductType.SimpleProduct)
                    {
                        <div class="card card-default">
                            <div class="card-body">
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="UnitPriceInclTax" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="UnitPriceInclTax" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="Quantity" />
                                    </div>
                                    <div class="col-md-9">
                                        <nop-editor asp-for="Quantity" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        var dataDict = new ViewDataDictionary(ViewData) { new("productId", Model.ProductId) };
                        @await Html.PartialAsync("_ProductAddAttributes.cshtml", Model.ProductAttributes, dataDict)
                        
                        <div class="card card-default">
                            <div class="card-body">
                                <div class="form-group row">
                                    <div class="col-md-9 offset-md-3">
                                        <button type="submit" class="btn btn-primary">
                                            @T("Plugins.Misc.RFQ.AddNewProduct")
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    else if (Model.ProductType == ProductType.GroupedProduct)
                    {
                        <div class="card card-default">
                            <div class="card-body">
                                Grouped products are not currently supported for adding to the quote
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="card card-default">
                            <div class="card-body">
                                This product type (unknown) is not currently supported for adding to the quote
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
    <input asp-for="QuoteId" type="hidden" />
</form>

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Misc.RFQ/Views/Admin/AddProductToQuote.cshtml
@model Nop.Plugin.Misc.RFQ.Models.Admin.ProductSearchModel

@{
    Layout = "_AdminLayout";
    //page title
    ViewBag.PageTitle = string.Format(T("Plugins.Misc.RFQ.AdminQuote.Products.AddNew.Title1").Text, Model.EntityId);
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName(RfqDefaults.QuotesAdminMenuSystemName);
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @string.Format(T("Plugins.Misc.RFQ.AdminQuote.Products.AddNew.Title1").Text, Model.EntityId)
        <small>
            <i class="fas fa-arrow-circle-left"></i>
            <a asp-action="AdminQuote" asp-route-id="@Model.EntityId">@T("Plugins.Misc.RFQ.AdminQuote.Products.AddNew.BackToQuote")</a>
        </small>
    </h1>
    <div class="float-right">
        &nbsp;
    </div>
</div>

@await Html.PartialAsync("_SelectProductToAdd.cshtml", Model)

<script>
    function addProductToRequest(productId) {
        //load "product details page" block
        var productDetailsActionUrl = '@Html.Raw(Url.Action("AddProductDetails", "RfqAdmin", new { quoteId = Model.EntityId, productId = "productidplaceholder" }))';
        productDetailsActionUrl = productDetailsActionUrl.replace("productidplaceholder", productId);
        setLocation(productDetailsActionUrl);
    }
</script>

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Misc.RFQ/Views/Admin/AdminQuote.cshtml
@using Nop.Plugin.Misc.RFQ.Models.Admin
@model QuoteModel

@{
    var title = string.Format(T("Plugins.Misc.RFQ.QuoteNumber").Text, Model.Id);

    Layout = "_AdminLayout";
    //page title
    ViewBag.PageTitle = title;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName(RfqDefaults.QuotesAdminMenuSystemName);

    const string hideInfoBlockAttributeName = "AdminQuote.HideInfoBlock";
    var customer = await workContext.GetCurrentCustomerAsync();
    var hideInfoBlock = await genericAttributeService.GetAttributeAsync<bool>(customer, hideInfoBlockAttributeName);
}

<div asp-validation-summary="All"></div>

<form asp-controller="RfqAdmin" asp-action="AdminQuote" method="post">
    <input asp-for="Id" type="hidden" />
    <div class="content-header clearfix">
        <h1 class="float-left">
            @title
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="AdminQuotes">@T("Plugins.Misc.RFQ.AdminQuote.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            @if (Model.DisplayAddNewProductButton)
            {
                <button type="submit" id="btnAddNewProduct" name="btnAddNewProduct" onclick="javascript:setLocation('@(Url.Action("AddProductToQuote", "RfqAdmin", new { quoteId = Model.Id }))'); return false;" class="btn btn-info">
                    <i class="far fa-plus-square"></i>
                    @T("Plugins.Misc.RFQ.AddNewProduct")
                </button>
            }
            @if (Model.DisplaySendQuoteButton)
            {
                <button type="submit"
                        name="sendQuote"
                        id="send-request"
                        formaction="@Url.Action("SendQuote")"
                        formmethod="post"
                        class="btn btn-info">
                    <i class="far fa-share-square"></i>
                    @T("Plugins.Misc.RFQ.SendQuote")
                </button>
            }
            @if (Model.DisplayDeleteQuoteButton)
            {
                <button type="submit"
                        id="delete-quote"
                        name="deleteQuote"
                        formaction="@Url.Action("DeleteQuote")"
                        formmethod="post"
                        class="btn btn-danger">
                    <i class="far fa-trash-alt"></i>
                    @T("Admin.Common.Delete")
                </button>
            }
            @if (Model.DisplaySaveButtons)
            {
                <button type="submit" name="save" class="btn btn-primary">
                    <i class="far fa-save"></i>
                    @T("Admin.Common.Save")
                </button>
                <button type="submit" name="save-continue" class="btn btn-primary">
                    <i class="far fa-save"></i>
                    @T("Admin.Common.SaveContinue")
                </button>
            }
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <nop-cards id="quote-cards">
                    <nop-card asp-name="quote-info" asp-icon="fas fa-info" asp-title="@T("Plugins.Misc.RFQ.CustomerQuote.Info")" asp-hide-block-attribute-name="@hideInfoBlockAttributeName" asp-hide="@hideInfoBlock" asp-advanced="false">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CustomerEmail"/>
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">
                                        <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.CustomerId">@(!string.IsNullOrEmpty(Model.CustomerEmail) ? Model.CustomerEmail : T("Admin.Customers.Guest").Text)</a>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CreatedOn"/>
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.CreatedOn</div>
                                </div>
                            </div>
                            @if (Model.Editable || Model.ExpirationDateUtc.HasValue)
                            {
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="ExpirationDateUtc"/>
                                    </div>
                                    @if (Model.Editable)
                                    {
                                        <div class="col-md-9">
                                            <nop-editor asp-for="ExpirationDateUtc"/>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="col-md-9">
                                            <div class="form-text-row">@Model.ExpirationDateUtc</div>
                                        </div>
                                    }
                                </div>
                            }
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Status"/>
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.Status</div>
                                </div>
                            </div>
                            @if (Model.RequestQuoteId.HasValue)
                            {
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="RequestQuoteId"/>
                                    </div>
                                    <div class="col-md-9">
                                        <div class="form-text-row"><a href="~/Admin/RfqAdmin/AdminRequest/@Model.RequestQuoteId.Value">#@Model.RequestQuoteId.Value</a></div>
                                    </div>
                                </div>
                            }
                            @if (Model.OrderId.HasValue)
                            {
                                <div class="form-group row">
                                    <div class="col-md-3">
                                        <nop-label asp-for="OrderId" />
                                    </div>
                                    <div class="col-md-9">
                                        <div class="form-text-row"><a href="~/Admin/Order/Edit/@Model.OrderId.Value">#@Model.OrderId.Value</a></div>
                                    </div>
                                </div>
                            }
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="AdminNotes" />
                                </div>
                                <div class="col-md-9">
                                    @if (Model.Editable)
                                    {
                                        <nop-textarea asp-for="AdminNotes"></nop-textarea>
                                    }
                                    else
                                    {
                                        <div class="form-text-row">
                                            @Html.Raw(Model.AdminNotes.Replace(Environment.NewLine, "<br />"))
                                        </div>
                                    }
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-12">
                                    <h3>@T("Plugins.Misc.RFQ.Products")</h3>
                                    @await Html.PartialAsync("_AdminQuote.Products.cshtml", Model)
                                </div>
                            </div>
                        </div>
                    </nop-card>
                </nop-cards>
            </div>
        </div>
    </section>
</form>

<nop-action-confirmation asp-button-id="send-request" />
<nop-action-confirmation asp-button-id="delete-quote" />

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Misc.RFQ/Views/Admin/Configure.cshtml
@model Nop.Plugin.Misc.RFQ.Models.Admin.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="RfqAdmin" asp-action="Configure" method="post">
    <section class="content">
        <div class="container-fluid">			
            <div class="card card-default">
                <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-3">
                            <nop-label asp-for="Enabled" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="Enabled" />
                            <span asp-validation-for="Enabled"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-9 offset-md-3">
                            <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                        </div>
                    </div>
                </div>
            </div>			
        </div>
    </section>
</form>

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Misc.RFQ/Views/Admin/_AdminQuote.Products.cshtml
@using Nop.Plugin.Misc.RFQ.Models.Admin
@model QuoteModel

<table class="table table-hover table-bordered">
    <thead>
    <tr>
        <th>@T("Plugins.Misc.RFQ.Product")</th>
        <th style="width: 10%">@T("Plugins.Misc.RFQ.AdminQuote.RequestedUnitPrice")</th>
        <th style="width: 10%">@T("Plugins.Misc.RFQ.AdminQuote.RequestedQty")</th>
        <th style="width: 10%">@T("Plugins.Misc.RFQ.OfferedUnitPrice")</th>
        <th style="width: 10%">@T("Plugins.Misc.RFQ.OfferedQty")</th>
        @if (Model.Editable)
        {
            <th style="width: 15%">@T("Admin.Common.Edit")</th>
        }
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Items)
    {
        <script>
		    $(function() {
			    toggleItemEdit(@item.Id, false);
		    });			
		</script>
	
        <tr>
            <td>
                <em><a asp-controller="Product" asp-action="Edit" asp-route-id="@item.ProductId">@item.ProductName</a></em>
                @if (!string.IsNullOrEmpty(item.ProductAttributeInfo))
                {
                    <p>
                        @Html.Raw(item.ProductAttributeInfo)
                    </p>
                }
            </td>
            <td>
                @item.RequestedUnitPrice
            </td>
            <td>
                <div>@item.RequestedQty</div>
            </td>
            
            <td>
                <div>@item.OfferedUnitPrice</div>
                <div id="pnlEditUnitPrice@(item.Id)">
                    <input name="unitPrice@(item.Id)" type="text" value="@item.OfferedUnitPriceValue" id="unitPrice@(item.Id)" class="form-control input-sm"/>
                </div>
            </td>
            <td>
                <div>@item.OfferedQty</div>
                <div id="pnlEditQuantity@(item.Id)">
                    <input name="quantity@(item.Id)" type="text" value="@item.OfferedQty" id="quantity@(item.Id)" class="form-control input-sm"/>
                </div>
            </td>

            @if (Model.Editable)
            {
                <td>
                    <button type="button" class="btn btn-default" onclick="toggleItemEdit(@item.Id, true)" id="btnEdit@(item.Id)">
                        <i class="fas fa-pencil-alt"></i>
                        @T("Admin.Common.Edit")
                    </button>

                    <button type="button" class="btn btn-default" name="btnDelete@(item.Id)" id="btnDelete@(item.Id)">
                        <i class="far fa-trash-alt"></i>
                        @T("Admin.Common.Delete")
                    </button>
                    <nop-action-confirmation asp-button-id="@("btnDelete" + item.Id)"/>

                    <button type="button" name="btnSave@(item.Id)" class="btn btn-default" id="btnSave@(item.Id)">
                        <i class="far fa-save"></i>
                        @T("Admin.Common.Save")
                    </button>
                    <nop-action-confirmation asp-button-id="@("btnSave" + item.Id)"/>

                    <button type="button" class="btn btn-default" onclick="toggleItemEdit(@item.Id, false)" id="btnCancel@(item.Id)">
                        <i class="fas fa-times"></i>
                        @T("Admin.Common.Cancel")
                    </button>
                </td>
            }
        </tr>
    }
    </tbody>
</table>

<script>
    function toggleItemEdit(itemId, editMode) {
        if (editMode) {                                                       
            $('#btnSave'+itemId).showElement();
            $('#btnCancel'+itemId).showElement();
            $('#pnlEditQuantity'+itemId).showElement();
            $('#quantity'+itemId).prop("disabled", false);
            $('#pnlEditUnitPrice'+itemId).showElement();
            $('#unitPrice'+itemId).prop("disabled", false);
            $('#btnEdit'+itemId).hideElement();
			$('#btnDelete'+itemId).hideElement();		
			
        } else {
            $('#btnSave'+itemId).hideElement();
            $('#btnCancel'+itemId).hideElement();
            $('#pnlEditQuantity'+itemId).hideElement();
            $('#quantity'+itemId).prop("disabled", true);
            $('#pnlEditUnitPrice'+itemId).hideElement();
            $('#unitPrice'+itemId).prop("disabled", true);
            $('#btnEdit'+itemId).showElement();     
			$('#btnDelete'+itemId).showElement();			
        }
        
        return false;
    }
</script>