source/repos/nopCommerce_Shop/src/Presentation/Nop.Web/Areas/Admin/Controllers/CustomerRoleController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Customers;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class CustomerRoleController : BaseAdminController
{
    #region Fields

    protected readonly ICustomerActivityService _customerActivityService;
    protected readonly ICustomerRoleModelFactory _customerRoleModelFactory;
    protected readonly ICustomerService _customerService;
    protected readonly ILocalizationService _localizationService;
    protected readonly INotificationService _notificationService;
    protected readonly IPermissionService _permissionService;
    protected readonly IProductService _productService;
    protected readonly IWorkContext _workContext;

    #endregion

    #region Ctor

    public CustomerRoleController(ICustomerActivityService customerActivityService,
        ICustomerRoleModelFactory customerRoleModelFactory,
        ICustomerService customerService,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IPermissionService permissionService,
        IProductService productService,
        IWorkContext workContext)
    {
        _customerActivityService = customerActivityService;
        _customerRoleModelFactory = customerRoleModelFactory;
        _customerService = customerService;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _permissionService = permissionService;
        _productService = productService;
        _workContext = workContext;
    }

    #endregion

    #region Methods

    public virtual IActionResult Index()
    {
        return RedirectToAction("List");
    }

    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_VIEW)]
    public virtual async Task<IActionResult> List()
    {
        //prepare model
        var model = await _customerRoleModelFactory.PrepareCustomerRoleSearchModelAsync(new CustomerRoleSearchModel());

        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_VIEW)]
    public virtual async Task<IActionResult> List(CustomerRoleSearchModel searchModel)
    {
        //prepare model
        var model = await _customerRoleModelFactory.PrepareCustomerRoleListModelAsync(searchModel);

        return Json(model);
    }

    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_CREATE_EDIT_DELETE)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> Create()
    {
        //prepare model
        var model = await _customerRoleModelFactory.PrepareCustomerRoleModelAsync(new CustomerRoleModel(), null);

        return View(model);
    }

    [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_CREATE_EDIT_DELETE)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> Create(CustomerRoleModel model, bool continueEditing)
    {
        if (ModelState.IsValid)
        {
            var customerRole = model.ToEntity<CustomerRole>();
            await _customerService.InsertCustomerRoleAsync(customerRole);

            //activity log
            await _customerActivityService.InsertActivityAsync("AddNewCustomerRole",
                string.Format(await _localizationService.GetResourceAsync("ActivityLog.AddNewCustomerRole"), customerRole.Name), customerRole);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Customers.CustomerRoles.Added"));

            return continueEditing ? RedirectToAction("Edit", new { id = customerRole.Id }) : RedirectToAction("List");
        }

        //prepare model
        model = await _customerRoleModelFactory.PrepareCustomerRoleModelAsync(model, null, true);

        //if we got this far, something failed, redisplay form
        return View(model);
    }

    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_VIEW)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> Edit(int id)
    {
        //try to get a customer role with the specified id
        var customerRole = await _customerService.GetCustomerRoleByIdAsync(id);
        if (customerRole == null)
            return RedirectToAction("List");

        //prepare model
        var model = await _customerRoleModelFactory.PrepareCustomerRoleModelAsync(null, customerRole);

        return View(model);
    }

    [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_CREATE_EDIT_DELETE)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> Edit(CustomerRoleModel model, bool continueEditing)
    {
        //try to get a customer role with the specified id
        var customerRole = await _customerService.GetCustomerRoleByIdAsync(model.Id);
        if (customerRole == null)
            return RedirectToAction("List");

        try
        {
            if (ModelState.IsValid)
            {
                if (customerRole.IsSystemRole && !model.Active)
                    throw new NopException(await _localizationService.GetResourceAsync("Admin.Customers.CustomerRoles.Fields.Active.CantEditSystem"));

                if (customerRole.IsSystemRole && !customerRole.SystemName.Equals(model.SystemName, StringComparison.InvariantCultureIgnoreCase))
                    throw new NopException(await _localizationService.GetResourceAsync("Admin.Customers.CustomerRoles.Fields.SystemName.CantEditSystem"));

                if (NopCustomerDefaults.RegisteredRoleName.Equals(customerRole.SystemName, StringComparison.InvariantCultureIgnoreCase) &&
                    model.PurchasedWithProductId > 0)
                    throw new NopException(await _localizationService.GetResourceAsync("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Registered"));

                customerRole = model.ToEntity(customerRole);
                await _customerService.UpdateCustomerRoleAsync(customerRole);

                //activity log
                await _customerActivityService.InsertActivityAsync("EditCustomerRole",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.EditCustomerRole"), customerRole.Name), customerRole);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Customers.CustomerRoles.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = customerRole.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = await _customerRoleModelFactory.PrepareCustomerRoleModelAsync(model, customerRole, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }
        catch (Exception exc)
        {
            await _notificationService.ErrorNotificationAsync(exc);
            return RedirectToAction("Edit", new { id = customerRole.Id });
        }
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_CREATE_EDIT_DELETE)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> Delete(int id)
    {
        //try to get a customer role with the specified id
        var customerRole = await _customerService.GetCustomerRoleByIdAsync(id);
        if (customerRole == null)
            return RedirectToAction("List");

        try
        {
            await _customerService.DeleteCustomerRoleAsync(customerRole);

            //activity log
            await _customerActivityService.InsertActivityAsync("DeleteCustomerRole",
                string.Format(await _localizationService.GetResourceAsync("ActivityLog.DeleteCustomerRole"), customerRole.Name), customerRole);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Customers.CustomerRoles.Deleted"));

            return RedirectToAction("List");
        }
        catch (Exception exc)
        {
            _notificationService.ErrorNotification(exc.Message);
            return RedirectToAction("Edit", new { id = customerRole.Id });
        }
    }

    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_VIEW)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> AssociateProductToCustomerRolePopup()
    {
        //prepare model
        var model = await _customerRoleModelFactory.PrepareCustomerRoleProductSearchModelAsync(new CustomerRoleProductSearchModel());

        return View(model);
    }

    [HttpPost]
    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_VIEW)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]
    public virtual async Task<IActionResult> AssociateProductToCustomerRolePopupList(CustomerRoleProductSearchModel searchModel)
    {
        //prepare model
        var model = await _customerRoleModelFactory.PrepareCustomerRoleProductListModelAsync(searchModel);

        return Json(model);
    }

    [HttpPost]
    [FormValueRequired("save")]
    [CheckPermission(StandardPermission.Customers.CUSTOMER_ROLES_CREATE_EDIT_DELETE)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_ACL)]

source/repos/nopCommerce_Shop/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/AssociateProductToCustomerRolePopup.cshtml
@model CustomerRoleProductSearchModel

@{
    Layout = "_AdminPopupLayout";
    
    //page title
    ViewBag.PageTitle = T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Choose").Text;
}

<form asp-controller="CustomerRole" asp-action="AssociateProductToCustomerRolePopup"
      asp-route-productIdInput="@Context.Request.Query["productIdInput"]"
      asp-route-productNameInput="@Context.Request.Query["productNameInput"]"
      asp-route-btnId="@Context.Request.Query["btnId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Choose")
        </h1>
        <div class="float-right">
            &nbsp;
        </div>
    </div>

    @if (ViewBag.RefreshPage == true)
    {
        <script>
            try {
                window.opener.document.getElementById('@(Context.Request.Query["productIdInput"])').value = '@(ViewBag.productId)';
                window.opener.document.getElementById('@(Context.Request.Query["productNameInput"])').innerHTML = '@(ViewBag.productName)';
                window.opener.document.getElementById('@(Context.Request.Query["btnId"])').click();
            }
            catch (e){}
            window.close();
        </script>
    }
    else
    {

        <input type="hidden" asp-for="AddProductToCustomerRoleModel.AssociatedToProductId" />
         <section class="content">
            <div class="container-fluid">
                    <div class="form-horizontal">
                        <div class="cards-group">
                            <div class="card card-default card-search card-popup">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group row">
                                                <div class="col-sm-5">
                                                    <nop-label asp-for="SearchProductName" />
                                                </div>
                                                <div class="col-sm-7">
                                                    <nop-editor asp-for="SearchProductName" />
                                                </div>
                                            </div>
                                            <div class="form-group row" @(Model.AvailableCategories.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                                <div class="col-sm-5">
                                                    <nop-label asp-for="SearchCategoryId" />
                                                </div>
                                                <div class="col-sm-7">
                                                    <nop-select asp-for="SearchCategoryId" asp-items="Model.AvailableCategories" />
                                                </div>
                                            </div>
                                            <div class="form-group row" @(Model.AvailableVendors.SelectionIsNotPossible() || Model.IsLoggedInAsVendor ? Html.Raw("style='display: none;'") : null)>
                                                <div class="col-sm-5">
                                                    <nop-label asp-for="SearchVendorId" />
                                                </div>
                                                <div class="col-sm-7">
                                                    <nop-select asp-for="SearchVendorId" asp-items="Model.AvailableVendors" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group row" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                                <div class="col-sm-5">
                                                    <nop-label asp-for="SearchStoreId" />
                                                </div>
                                                <div class="col-sm-7">
                                                    <nop-select asp-for="SearchStoreId" asp-items="Model.AvailableStores" />
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-5">
                                                    <nop-label asp-for="SearchProductTypeId" />
                                                </div>
                                                <div class="col-sm-7">
                                                    <nop-select asp-for="SearchProductTypeId" asp-items="Model.AvailableProductTypes" />
                                                </div>
                                            </div>
                                            <div class="form-group row" @(Model.AvailableManufacturers.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                                <div class="col-sm-5">
                                                    <nop-label asp-for="SearchManufacturerId" />
                                                </div>
                                                <div class="col-sm-7">
                                                    <nop-select asp-for="SearchManufacturerId" asp-items="Model.AvailableManufacturers" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <button type="button" id="search-products" class="btn btn-primary btn-search">
                                                <i class="fas fa-magnifying-glass"></i>
                                                @T("Admin.Common.Search")
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card card-default">
                                <div class="card-body">
                                    @await Html.PartialAsync("Table", new DataTablesModel
                                    {
                                        Name = "products-grid",
                                        UrlRead = new DataUrl("AssociateProductToCustomerRolePopupList", "CustomerRole", null),
                                        SearchButtonId = "search-products",
                                        Length = Model.PageSize,
                                        LengthMenu = Model.AvailablePageSizes,
                                        Filters = new List<FilterParameter>
                                        {
                                            new FilterParameter(nameof(Model.SearchProductName)),
                                            new FilterParameter(nameof(Model.SearchCategoryId)),
                                            new FilterParameter(nameof(Model.SearchManufacturerId)),
                                            new FilterParameter(nameof(Model.SearchStoreId)),
                                            new FilterParameter(nameof(Model.SearchVendorId)),
                                            new FilterParameter(nameof(Model.SearchProductTypeId))
                                        },
                                        ColumnCollection = new List<ColumnProperty>
                                        {
                                            new ColumnProperty(nameof(ProductModel.Id))
                                            {
                                                Title = T("Admin.Common.Select").Text,
                                                Render = new RenderCustom("renderColumnSelectProduct"),
                                                ClassName =  NopColumnClassDefaults.Button,
                                                Width = "50",
                                            },
                                            new ColumnProperty(nameof(ProductModel.Name))
                                            {
                                                Title = T("Admin.Catalog.Products.Fields.Name").Text
                                            },
                                            new ColumnProperty(nameof(ProductModel.Published))
                                            {
                                                Title = T("Admin.Catalog.Products.Fields.Published").Text,
                                                Width = "100",
                                                ClassName = NopColumnClassDefaults.CenterAll,
                                                Render = new RenderBoolean()
                                            }
                                        }
                                    })
                                    <script>
                                        function renderColumnSelectProduct(data, type, row, meta) {
                                            return '<button type="button" onclick="selectAssociatedProduct(' + row.Id + ' )" class="btn btn-default">@T("Admin.Common.Select").Text</button>';
                                        }
                                        function selectAssociatedProduct(productid) {
                                            $("#@Html.IdFor(model => model.AddProductToCustomerRoleModel.AssociatedToProductId)").val(productid);
                                            $('#save').trigger('click');
                                        }
                                    </script>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" id="save" name="save" class="btn btn-default" style="display: none">
                                        @T("Admin.Common.Save")
                                    </button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
        </section>
    }
</form>

source/repos/nopCommerce_Shop/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/Create.cshtml
@model CustomerRoleModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Customers.CustomerRoles.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Customer roles");
}

<form asp-controller="CustomerRole" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Customers.CustomerRoles.AddNew") 
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Customers.CustomerRoles.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.CustomerRoleDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

source/repos/nopCommerce_Shop/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/Edit.cshtml
@model CustomerRoleModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Customers.CustomerRoles.EditCustomerRoleDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Customer roles");
}

<form asp-controller="CustomerRole" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Customers.CustomerRoles.EditCustomerRoleDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Customers.CustomerRoles.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-floppy-disk"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="customerrole-delete" class="btn btn-danger">
                <i class="far fa-trash-can"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.CustomerRoleDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="customerrole-delete" />

source/repos/nopCommerce_Shop/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/List.cshtml
@model CustomerRoleSearchModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Customers.CustomerRoles").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Customer roles");
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Admin.Customers.CustomerRoles")
    </h1>
    <div class="float-right">
        <a asp-action="Create" class="btn btn-primary">
            <i class="fas fa-square-plus"></i>
            @T("Admin.Common.AddNew")
        </a>
        @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.CustomerRoleListButtons, additionalData = Model })
    </div>
</div>

<section class="content">
    <div class="container-fluid">
    <div class="form-horizontal">
        <div class="cards-group">
            <div class="card card-default">
                <div class="card-body">
                    <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.CustomerRoles", Docs.CustomerRoles + Utm.OnAdmin)" />

                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "customerroles-grid",
                        UrlRead = new DataUrl("List", "CustomerRole", null),
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(CustomerRoleModel.Name))
                            {
                                Title = T("Admin.Customers.CustomerRoles.Fields.Name").Text,
                                Width = "300"
                            },
                            new ColumnProperty(nameof(CustomerRoleModel.FreeShipping))
                            {
                                Title = T("Admin.Customers.CustomerRoles.Fields.FreeShipping").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(CustomerRoleModel.TaxExempt))
                            {
                                Title = T("Admin.Customers.CustomerRoles.Fields.TaxExempt").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(CustomerRoleModel.Active))
                            {
                                Title = T("Admin.Customers.CustomerRoles.Fields.Active").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(CustomerRoleModel.IsSystemRole))
                            {
                                Title = T("Admin.Customers.CustomerRoles.Fields.IsSystemRole").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(CustomerRoleModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("~/Admin/CustomerRole/Edit"))
                            }
                        }
                    })
                </div>
            </div>
        </div>
    </div>
</div>
</section>