source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Models/Public/ApplePayModel.cs
using Nop.Plugin.Payments.PayPalCommerce.Domain;

namespace Nop.Plugin.Payments.PayPalCommerce.Models.Public;

/// <summary>
/// Represents the Apple Pay model
/// </summary>
public record ApplePayModel : OrderModel
{
    #region Properties

    public ButtonPlacement Placement { get; set; }

    public string CurrencyCode { get; set; }

    public Contact BillingAddress { get; set; } = new();

    public Contact ShippingAddress { get; set; } = new();

    public List<(string Id, string Label, string Description, string Price)> ShippingOptions { get; set; } = new();

    public List<(string Type, string Price, string Status, string Label)> Items { get; set; } = new();

    #endregion
}

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Models/Public/OrderApprovedModel.cs
namespace Nop.Plugin.Payments.PayPalCommerce.Models.Public;

/// <summary>
/// Represents the order approved model
/// </summary>
public record OrderApprovedModel : OrderModel
{
    #region Properties

    public bool PayNow { get; set; }

    #endregion
}

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Components/Public/ButtonsViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Nop.Plugin.Payments.PayPalCommerce.Domain;
using Nop.Plugin.Payments.PayPalCommerce.Factories;
using Nop.Plugin.Payments.PayPalCommerce.Models.Public;
using Nop.Plugin.Payments.PayPalCommerce.Services;
using Nop.Core.Http;
using Nop.Services.Catalog;
using Nop.Web.Framework.Components;
using Nop.Web.Framework.Infrastructure;
using Nop.Web.Models.Catalog;

namespace Nop.Plugin.Payments.PayPalCommerce.Components.Public;

/// <summary>
/// Represents the view component to display PayPal buttons in the public store
/// </summary>
public class ButtonsViewComponent : NopViewComponent
{
    #region Fields

    private readonly IProductService _productService;
    private readonly PayPalCommerceModelFactory _modelFactory;
    private readonly PayPalCommerceServiceManager _serviceManager;
    private readonly PayPalCommerceSettings _settings;

    #endregion

    #region Ctor

    public ButtonsViewComponent(IProductService productService,
        PayPalCommerceModelFactory modelFactory,
        PayPalCommerceServiceManager serviceManager,
        PayPalCommerceSettings settings)
    {
        _productService = productService;
        _modelFactory = modelFactory;
        _serviceManager = serviceManager;
        _settings = settings;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Invoke view component
    /// </summary>
    /// <param name="widgetZone">Widget zone name</param>
    /// <param name="additionalData">Additional data</param>
    /// <returns>
    /// A task that represents the asynchronous operation
    /// The task result contains the view component result
    /// </returns>
    public async Task<IViewComponentResult> InvokeAsync(string widgetZone, object additionalData)
    {
        var (active, _) = await _serviceManager.IsActiveAsync(_settings);
        if (!active)
            return Content(string.Empty);

        PaymentInfoModel model = null;

        if (widgetZone.Equals(PublicWidgetZones.ProductDetailsAddInfo))
        {
            if (_settings.DisplayButtonsOnProductDetails)
            {
                var productId = additionalData is ProductDetailsModel.AddToCartModel product ? (int?)product.ProductId : null;
                if (productId is null || (await _productService.GetProductByIdAsync(productId ?? 0))?.ParentGroupedProductId == 0)
                    model = await _modelFactory.PreparePaymentInfoModelAsync(ButtonPlacement.Product, productId);
            }
        }
        else if (widgetZone.Equals(PublicWidgetZones.OrderSummaryContentBefore))
        {
            if (_settings.DisplayButtonsOnShoppingCart)
            {
                var routeName = HttpContext.GetEndpoint()?.Metadata.GetMetadata<RouteNameMetadata>()?.RouteName;
                if (routeName == NopRouteNames.General.CART)
                    model = await _modelFactory.PreparePaymentInfoModelAsync(ButtonPlacement.Cart);
            }
        }
        else
        {
            if (_settings.DisplayButtonsOnPaymentMethod)
                model = await _modelFactory.PreparePaymentInfoModelAsync(ButtonPlacement.PaymentMethod);
        }

        if (model?.Cart.IsRecurring is null)
            return Content(string.Empty);

        if (model.Cart.IsRecurring == true)
            return View("~/Plugins/Payments.PayPalCommerce/Views/Public/_Buttons.Recurring.cshtml", model);

        return View("~/Plugins/Payments.PayPalCommerce/Views/Public/_Buttons.cshtml", model);
    }

    #endregion
}

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Components/Public/LogoViewComponent.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Nop.Plugin.Payments.PayPalCommerce.Services;
using Nop.Web.Framework.Components;
using Nop.Web.Framework.Infrastructure;

namespace Nop.Plugin.Payments.PayPalCommerce.Components.Public;

/// <summary>
/// Represents the view component to display PayPal logo in the public store
/// </summary>
public class LogoViewComponent : NopViewComponent
{
    #region Fields

    private readonly PayPalCommerceSettings _settings;
    private readonly PayPalCommerceServiceManager _serviceManager;

    #endregion

    #region Ctor

    public LogoViewComponent(PayPalCommerceSettings settings,
        PayPalCommerceServiceManager serviceManager)
    {
        _settings = settings;
        _serviceManager = serviceManager;
    }

    #endregion

    #region Methods

    /// <summary>
    /// Invoke view component
    /// </summary>
    /// <param name="widgetZone">Widget zone name</param>
    /// <param name="additionalData">Additional data</param>
    /// <returns>
    /// A task that represents the asynchronous operation
    /// The task result contains the view component result
    /// </returns>
    public async Task<IViewComponentResult> InvokeAsync(string widgetZone, object additionalData)
    {
        var (active, _) = await _serviceManager.IsActiveAsync(_settings);
        if (!active)
            return Content(string.Empty);

        var script = widgetZone.Equals(PublicWidgetZones.HeaderLinksBefore) && _settings.DisplayLogoInHeaderLinks
            ? _settings.LogoInHeaderLinks
            : widgetZone.Equals(PublicWidgetZones.Footer) && _settings.DisplayLogoInFooter
            ? _settings.LogoInFooter
            : null;

        return new HtmlContentViewComponentResult(new HtmlString(script ?? string.Empty));
    }

    #endregion
}

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Components/Public/PaymentInfoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework.Components;

namespace Nop.Plugin.Payments.PayPalCommerce.Components.Public;

/// <summary>
/// Represents the view component to display payment info in the public store
/// </summary>
public class PaymentInfoViewComponent : NopViewComponent
{
    #region Methods

    /// <summary>
    /// Invoke view component
    /// </summary>
    /// <param name="widgetZone">Widget zone name</param>
    /// <param name="additionalData">Additional data</param>
    /// <returns>
    /// A task that represents the asynchronous operation
    /// The task result contains the view component result
    /// </returns>
    public IViewComponentResult Invoke(string widgetZone, object additionalData)
    {
        return View("~/Plugins/Payments.PayPalCommerce/Views/Public/PaymentInfo.cshtml");
    }

    #endregion
}

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Controllers/PayPalCommercePublicController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Http;
using Nop.Plugin.Payments.PayPalCommerce.Domain;
using Nop.Plugin.Payments.PayPalCommerce.Factories;
using Nop.Plugin.Payments.PayPalCommerce.Models.Public;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.PayPalCommerce.Controllers;

[AutoValidateAntiforgeryToken]
public class PayPalCommercePublicController : BasePublicController
{
    #region Fields

    private readonly ILocalizationService _localizationService;
    private readonly INotificationService _notificationService;
    private readonly IWebHelper _webHelper;
    private readonly PayPalCommerceModelFactory _modelFactory;

    #endregion

    #region Ctor

    public PayPalCommercePublicController(ILocalizationService localizationService,
        INotificationService notificationService,
        IWebHelper webHelper,
        PayPalCommerceModelFactory modelFactory)
    {
        _localizationService = localizationService;
        _notificationService = notificationService;
        _webHelper = webHelper;
        _modelFactory = modelFactory;
    }

    #endregion

    #region Methods

    #region Checkout

    public async Task<IActionResult> PluginPaymentInfo()
    {
        var model = await _modelFactory.PrepareCheckoutPaymentInfoModelAsync();

        return View("~/Plugins/Payments.PayPalCommerce/Views/Public/PluginPaymentInfo.cshtml", model);
    }

    [CheckLanguageSeoCode(ignore: true)]
    public async Task<IActionResult> ValidateShoppingCart()
    {
        var warnings = await _modelFactory.GetShoppingCartWarningsAsync();
        if (warnings?.Any() ?? false)
            return ErrorJson(warnings.ToArray());

        return Json(new { success = true });
    }

    [HttpPost]
    public async Task<IActionResult> CreateOrder(int placement, string paymentSource, int cardId, bool saveCard)
    {
        var model = await _modelFactory.PrepareOrderModelAsync((ButtonPlacement)placement, null, paymentSource, cardId, saveCard);
        if (model.LoginIsRequired)
            return Json(new { redirect = Url.RouteUrl(NopRouteNames.General.LOGIN, new { returnUrl = Url.RouteUrl(NopRouteNames.General.CART) }) });

        if (!model.CheckoutIsEnabled)
            return Json(new { redirect = Url.RouteUrl(NopRouteNames.General.CART) });

        if (!string.IsNullOrEmpty(model.Error))
            return ErrorJson(model.Error);

        //customer can complete 3D Secure if prompted
        if (cardId > 0 && !string.IsNullOrEmpty(model.PayerActionUrl))
            return Json(new { redirect = model.PayerActionUrl });

        return Json(new { orderId = model.OrderId, status = model.Status });
    }

    [HttpPost]
    public async Task<IActionResult> GetOrderStatus(int placement, string orderId)
    {
        var model = await _modelFactory.PrepareOrderModelAsync((ButtonPlacement)placement, orderId, null, null, false);
        if (!string.IsNullOrEmpty(model.Error))
            return ErrorJson(model.Error);

        return Json(new { status = model.Status, payerAction = model.PayerActionUrl });
    }

    [HttpPost]
    public async Task<IActionResult> UpdateOrderShipping(OrderShippingModel model)
    {
        model = await _modelFactory.PrepareOrderShippingModelAsync(model);
        if (!string.IsNullOrEmpty(model.Error))
            return ErrorJson(model.Error);

        return Json(new { success = true });
    }

    [HttpPost]
    public async Task<IActionResult> ApproveOrder(string orderId, string liabilityShift)
    {
        var model = await _modelFactory.PrepareOrderApprovedModelAsync(orderId, liabilityShift);
        if (model.LoginIsRequired)
            return Json(new { redirect = Url.RouteUrl(NopRouteNames.General.LOGIN, new { returnUrl = Url.RouteUrl(NopRouteNames.General.CART) }) });

        if (!model.CheckoutIsEnabled)
            return Json(new { redirect = Url.RouteUrl(NopRouteNames.General.CART) });

        if (!string.IsNullOrEmpty(model.Error))
            return ErrorJson(model.Error);

        //order is approved but the customer must confirm it before (if not yet completed)
        if (!model.PayNow)
        {
            return Json(new
            {
                redirect = Url.RouteUrl(PayPalCommerceDefaults.Route.ConfirmOrder, new { orderId = model.OrderId, liabilityShift = liabilityShift })
            });
        }

        //or pay it right now
        var completedModel = await _modelFactory.PrepareOrderCompletedModelAsync(orderId, liabilityShift);
        if (!string.IsNullOrEmpty(completedModel.Error))
            return ErrorJson(completedModel.Error);

        return Json(new { redirect = Url.RouteUrl(NopRouteNames.Standard.CHECKOUT_COMPLETED, new { orderId = completedModel.OrderId }) });
    }

    public async Task<IActionResult> ConfirmOrder(string orderId, string token, string liabilityShift, bool approve)
    {
        if (string.IsNullOrEmpty(liabilityShift))
            liabilityShift = _webHelper.QueryString<string>("liability_shift");

        var model = await _modelFactory.PrepareOrderConfirmModelAsync(orderId, token, liabilityShift, approve);
        if (model.LoginIsRequired)
            return RedirectToRoute(NopRouteNames.General.LOGIN, new { returnUrl = Url.RouteUrl(NopRouteNames.General.CART) });

        if (!model.CheckoutIsEnabled)
            return RedirectToRoute(NopRouteNames.General.CART);

        if (!string.IsNullOrEmpty(model.Error))
            _notificationService.ErrorNotification(model.Error);

        return View("~/Plugins/Payments.PayPalCommerce/Views/Public/ConfirmOrder.cshtml", model);
    }

    [ValidateCaptcha]
    [HttpPost]
    public async Task<IActionResult> ConfirmOrderPost(string orderId, string orderGuid, string liabilityShift, bool captchaValid)
    {
        var model = await _modelFactory.PrepareOrderConfirmModelAsync(orderId, orderGuid, null, false);
        if (model.LoginIsRequired)
            return RedirectToRoute(NopRouteNames.General.LOGIN, new { returnUrl = Url.RouteUrl(NopRouteNames.General.CART) });

        if (!model.CheckoutIsEnabled)
            return RedirectToRoute(NopRouteNames.General.CART);

        if (!string.IsNullOrEmpty(model.Error))
            _notificationService.ErrorNotification(model.Error);

        if (model.DisplayCaptcha && !captchaValid)
        {
            model.Warnings.Add(await _localizationService.GetResourceAsync("Common.WrongCaptchaMessage"));
            return View("~/Plugins/Payments.PayPalCommerce/Views/Public/ConfirmOrder.cshtml", model);
        }

        var completedModel = await _modelFactory.PrepareOrderCompletedModelAsync(orderId, liabilityShift);

        if (!string.IsNullOrEmpty(completedModel.Error))
        {
            _notificationService.ErrorNotification(completedModel.Error);
            return View("~/Plugins/Payments.PayPalCommerce/Views/Public/ConfirmOrder.cshtml", model);
        }

        if (!string.IsNullOrEmpty(completedModel.Warning))
            _notificationService.ErrorNotification(completedModel.Warning);

        return RedirectToRoute(NopRouteNames.Standard.CHECKOUT_COMPLETED, new { orderId = completedModel.OrderId });
    }

    [HttpPost]
    public async Task<IActionResult> AppleTransactionInfo(int placement)
    {
        var model = await _modelFactory.PrepareApplePayModelAsync((ButtonPlacement)placement);
        if (model.LoginIsRequired)
            return Json(new { redirect = Url.RouteUrl(NopRouteNames.General.LOGIN, new { returnUrl = Url.RouteUrl(NopRouteNames.General.CART) }) });

        if (!model.CheckoutIsEnabled)
            return Json(new { redirect = Url.RouteUrl(NopRouteNames.General.CART) });

        if (!string.IsNullOrEmpty(model.Error))
            return ErrorJson(model.Error);

        var totalItem = model.Items.FirstOrDefault(item => item.Type == "TOTAL");
        var items = model.Items.Where(item => item.Type != "TOTAL");

        var transactionInfo = new
        {
            currencyCode = model.CurrencyCode,
            billingContact = model.BillingAddress is null ? null : new
            {
                emailAddress = model.BillingAddress.Email,
                givenName = model.BillingAddress.FirstName,
                familyName = model.BillingAddress.LastName,
                addressLines = model.BillingAddress.AddressLines?.Where(line => !string.IsNullOrEmpty(line)).ToArray(),
                locality = model.BillingAddress.City,
                subAdministrativeArea = model.BillingAddress.County,
                administrativeArea = model.BillingAddress.State,
                countryCode = model.BillingAddress.Country,
                postalCode = model.BillingAddress.PostalCode
            },
            shippingContact = model.ShippingAddress is null ? null : new
            {
                emailAddress = model.ShippingAddress.Email,
                givenName = model.ShippingAddress.FirstName,
                familyName = model.ShippingAddress.LastName,
                addressLines = model.ShippingAddress.AddressLines?.Where(line => !string.IsNullOrEmpty(line)).ToArray(),
                locality = model.ShippingAddress.City,
                administrativeArea = model.ShippingAddress.State,
                countryCode = model.ShippingAddress.Country,
                postalCode = model.ShippingAddress.PostalCode
            },
            //shippingType = model.ShippingAddress is null ? null : (model.ShippingAddress.PickupInStore ? "storePickup" : "shipping"),
            //shippingContactEditingMode = model.ShippingAddress is null ? null : "storePickup",
            shippingMethods = model.ShippingOptions
                ?.Select(option => new { identifier = option.Id, amount = option.Price, label = option.Label, detail = option.Description })
                .ToArray(),

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Public/ConfirmOrder.cshtml
@model OrderConfirmModel
@inject INopUrlHelper NopUrl

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";
    NopHtml.AddTitleParts(T("PageTitle.Checkout").Text);
}

<div class="page checkout-page order-confirm-page">
    <div class="page-title">
        <h1>@T("Checkout.ConfirmYourOrder")</h1>
    </div>
    <div class="page-body checkout-data">
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutConfirmTop, additionalData = Model })
        <div class="section confirm-order">
            <form asp-controller="PayPalCommercePublic" asp-action="ConfirmOrderPost" method="post" id="confirm-order-form">
                <input asp-for="OrderId" type="hidden" />
                <input asp-for="OrderGuid" type="hidden" />
                <input asp-for="LiabilityShift" type="hidden" />
                <script asp-location="Footer">
                    $(function () {
                        $('#confirm-order-form').submit(function () {
                            $('input[type=submit]', this).attr('disabled', 'disabled');
                        });

                        $('.confirm-order-next-step-button').on('click', function () {
                            var termOfServiceOk = true;
                            if ($('#termsofservice').length > 0) {
                                if (!$('#termsofservice').is(':checked')) {
                                    $("#terms-of-service-warning-box").dialog();
                                    termOfServiceOk = false;
                                } else {
                                    termOfServiceOk = true;
                                }
                            }
                            if (termOfServiceOk) {
                                return true;
                            } else {
                                return false;
                            }
                        });
                    });
                </script>
                @if (!string.IsNullOrEmpty(Model.MinOrderTotalWarning))
                {
                    <span class="min-order-warning">@Model.MinOrderTotalWarning</span>
                }
                else
                {
                    if (Model.TermsOfServiceOnOrderConfirmPage)
                    {
                        <div id="terms-of-service-warning-box" title="@T("Checkout.TermsOfService")" style="display: none;">
                            <p>@T("Checkout.TermsOfService.PleaseAccept")</p>
                        </div>
                        <div class="terms-of-service">
                            <input id="termsofservice" type="checkbox" name="termsofservice" />
                            <label for="termsofservice">@T("Checkout.TermsOfService.IAccept")</label>
                            @if (Model.TermsOfServicePopup)
                            {
                                <a class="read" id="read-terms">@T("Checkout.TermsOfService.Read")</a>
                                <script asp-location="Footer">
                                    $(function () {
                                        $('#read-terms').on('click', function (e) {
                                            e.preventDefault();
                                            displayPopupContentFromUrl('@Url.RouteUrl(NopRouteNames.Ajax.TOPIC_POPUP, new { SystemName = "conditionsofuse" })', '@T("Checkout.TermsOfService")');
                                        });
                                    });
                                </script>
                            }
                            else
                            {
                                <a class="read" id="read-terms" href="@await NopUrl.RouteTopicUrlAsync("conditionsofuse")">@T("Checkout.TermsOfService.Read")</a>
                            }
                        </div>
                    }
                    <div class="buttons">
                        <button type="submit" name="nextstep" class="button-1 confirm-order-next-step-button">@T("Checkout.ConfirmButton")</button>
                    </div>
                    <script asp-location="Footer">
                        $('#confirm-order-form').on('submit', function () {
                            var button = $(this).find('button[type="submit"][name="nextstep"]');
                            setTimeout(function () {
                                button.prop('disabled', true);
                            }, 0);
                        });
                    </script>
                    if (Model.DisplayCaptcha)
                    {
                        <nop-captcha />
                    }
                }
                @if (Model.Warnings.Any())
                {
                    <div class="message-error">
                        <ul>
                            @foreach (var warning in Model.Warnings)
                            {
                                <li>@warning</li>
                            }
                        </ul>
                    </div>
                }
            </form>
        </div>
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutConfirmBottom, additionalData = Model })
        <div class="section order-summary">
            @await Component.InvokeAsync(typeof(OrderSummaryViewComponent), new { prepareAndDisplayOrderReviewData = true })
        </div>
    </div>
</div>

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Public/PaymentInfo.cshtml
@{
    Layout = "";
}

<script asp-location="Footer">
    $(function () {
        $('button.payment-info-next-step-button').hide();
        window.location = '@(Url.RouteUrl(PayPalCommerceDefaults.Route.PaymentInfo))';
    });
</script>

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Public/PaymentTokens.cshtml
@model PaymentTokenListModel

@{
    Layout = "_ColumnsTwo";
    NopHtml.AddTitleParts(T("Plugins.Payments.PayPalCommerce.PaymentTokens").Text);
    NopHtml.AppendPageCssClassParts("html-account-page");
    NopHtml.AppendPageCssClassParts("paypal-payment-tokens-page");
}

@section left
{
    @(await Component.InvokeAsync(typeof(CustomerNavigationViewComponent), new { selectedTabId = PayPalCommerceDefaults.PaymentTokensMenuTab }))
}

<div class="page account-page order-list-page">
    <div class="page-title">
        <h1>@T("Account.MyAccount") - @T("Plugins.Payments.PayPalCommerce.PaymentTokens")</h1>
    </div>
    <div class="page-body">
        @if (Model.PaymentTokens.Any())
        {
            <div class="order-list">
                @foreach (var token in Model.PaymentTokens)
                {
                    <div class="section order-item">
                        <h2 class="title">
                            @token.Type
                        </h2>
                        <ul class="info">
                            <li>@T("Plugins.Payments.PayPalCommerce.PaymentTokens.Title"): <span class="order-status">@token.Title</span></li>
                            <li>@T("Plugins.Payments.PayPalCommerce.PaymentTokens.Expiration"): <span class="order-date">@token.Expiration</span></li>
                            @if (token.IsPrimaryMethod)
                            {
                                <li>@T("Plugins.Payments.PayPalCommerce.PaymentTokens.Default")</li>
                            }
                        </ul>
                        <div class="buttons">
                            @if (!token.IsPrimaryMethod)
                            {
                                <button type="button" class="button-2 edit-address-button" onclick="markDefaultPaymentToken(@(token.Id))">@T("Plugins.Payments.PayPalCommerce.PaymentTokens.MarkDefault")</button>
                            }
                            <button type="button" class="button-2 order-details-button" onclick="deletePaymentToken(@(token.Id))">@T("Common.Delete")</button>
                        </div>
                    </div>
                }
            </div>
            <script asp-location="Footer">
                function markDefaultPaymentToken(tokenId) {
                    if (confirm('@T("Common.AreYouSure")')) {
                        var postData = {
                            tokenId: tokenId
                        };
                        addAntiForgeryToken(postData);
                        $.ajax({
                            async: false,
                            type: 'POST',
                            url: '@(Url.Action("PaymentTokensMarkDefault", "PayPalCommercePublic"))',
                            data: postData,
                            success: function (data, textStatus, jqXHR) {
                                if (data.error) {
                                    displayBarNotification(data.error, 'error', 0);
                                }
                                else if (data.redirect) {
                                    setLocation(data.redirect);
                                }
                            },
                            error: function (jqXHR, textStatus, errorThrown) {
                                if (errorThrown) {
                                    displayBarNotification(errorThrown, 'error', 0);
                                } else {
                                    displayBarNotification(textStatus, 'error', 0);
                                }
                            }
                        });
                    }
                }

                function deletePaymentToken(tokenId) {
                    if (confirm('@T("Common.AreYouSure")')) {
                        var postData = {
                            tokenId: tokenId
                        };
                        addAntiForgeryToken(postData);
                        $.ajax({
                            async: false,
                            type: 'POST',
                            url: '@(Url.Action("PaymentTokensDelete", "PayPalCommercePublic"))',
                            data: postData,
                            success: function (data, textStatus, jqXHR) {
                                if (data.error) {
                                    displayBarNotification(data.error, 'error', 0);
                                }
                                else if (data.redirect) {
                                    setLocation(data.redirect);
                                }
                            },
                            error: function (jqXHR, textStatus, errorThrown) {
                                if (errorThrown) {
                                    displayBarNotification(errorThrown, 'error', 0);
                                } else {
                                    displayBarNotification(textStatus, 'error', 0);
                                }
                            }
                        });
                    }
                }
            </script>
        }
        else
        {
            <div class="no-data">
                @T("Plugins.Payments.PayPalCommerce.PaymentTokens.None")
            </div>
        }
    </div>
</div>

source/repos/nopCommerce_Shop/src/Plugins/Nop.Plugin.Payments.PayPalCommerce/Views/Public/PluginPaymentInfo.cshtml
@model Nop.Web.Models.Checkout.CheckoutPaymentInfoModel

@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";

    NopHtml.AddTitleParts(T("PageTitle.Checkout").Text);
}

<div class="page checkout-page payment-info-page">
    <div class="page-title">
        <h1>@T("Checkout.PaymentInfo")</h1>
    </div>
    <div class="page-body checkout-data">
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutPaymentInfoTop, additionalData = Model })
        <div class="section payment-info">
            <div class="info">
                @await Component.InvokeAsync(typeof(ButtonsViewComponent), new { widgetZone = "paypal_payment_info" })
            </div>
        </div>
        @await Component.InvokeAsync(typeof(WidgetViewComponent), new { widgetZone = PublicWidgetZones.CheckoutPaymentInfoBottom, additionalData = Model })
        <div class="section order-summary">
            <h2 class="title">
                @T("Checkout.OrderSummary")
            </h2>
            @await Component.InvokeAsync(typeof(OrderSummaryViewComponent))
        </div>
    </div>
</div>